# Generated by Django 4.0.6 on 2022-07-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliant_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='response',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
