# Generated by Django 4.0.6 on 2022-07-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliant_app', '0003_alter_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.IntegerField(choices=[(1, 'Solved'), (2, 'InProgress'), (3, 'Pending')], default=3),
        ),
    ]
